### PR TITLE
feat: add localization editor and ide extension

### PR DESCRIPTION
**Pull request by NilsJacobsen**
> Hi together, let me know what I need to change in order to merge this

## Added a [localization editor](https://inlang.com/m/tdozzpar) & [ide extension](https://inlang.com/m/r7kp499g) for better i18n handling

- Faster message extraction
- Continuous i18n process improvements
- Improved translation status

### Editor -> Fink Translation Editor ([Open Editor](https://fink.inlang.com/github.com/NilsJacobsen/veganify))
image

### IDE Extension
image

## What I added
- Added `project.inlang/settings.json` file to configure the [inlang](https://inlang.com/) project.
- `repo id` file was generated by the SDK
- Added the extension to the vscode recommendations, so every contributor con benefit

## All opt-in
- I didn't change you setup, everybody can use what they want (opt-in)
- It's only a config

### CODE REVIEW

**Comment by philipbrembeck** [comment]
Hi @NilsJacobsen 
Thanks a lot for contributing! How does the web-application exactly work, does it open a PR with changed/newly added translations?

**Comment by NilsJacobsen** [comment]
Hi @philipbrembeck,

> Thanks a lot for contributing! How does the web-application exactly work, does it open a PR with changed/newly added translations?

The editor can push changes or opens a PR based on your rights.

**Comment by philipbrembeck** [comment]
> Hi @philipbrembeck,
> 
> > Thanks a lot for contributing! How does the web-application exactly work, does it open a PR with changed/newly added translations?
> 
> The editor can push changes or opens a PR based on your rights.

Sounds nice, I'll bring it to Staging 😊

**Review by philipbrembeck — APPROVED** [review]

**Comment by NilsJacobsen** [comment]
@philipbrembeck does it make sense to add this status badge?

```txt
[![inlang status badge](https://badge.inlang.com/?url=github.com/nilsjacobsen/veganify)](https://fink.inlang.com/github.com/nilsjacobsen/veganify?ref=badge)
```

image

can be generated here: https://inlang.com/m/zu942ln6/app-inlang-badge

**Comment by philipbrembeck** [comment]
Yes, I'll add it 😊

**Pull request merged**
